# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zhao Yang's homepage!
name: Zhao Yang
email1: cnrgc@163.com 
email2: sxzhaoyang@gmail.com
location: Beijing, P.R.China
company: Intelligent and Connected Vehicle Device of China(Chengdu) Technology Co.,Ltd
company_url: https://www.cicvd.com/
github_url: https://github.com/youngbug
csdn_page: https://blog.csdn.net/youngbug
juejin_page: https://juejin.cn/user/3334166892253240
weibo: https://weibo.com/u/1649423232
weibo_name: 詹天佐
telegram: youngbug
description: This is Zhao Yang's homepage
favicon: youngbug.gif # Image must be in assets/images

url: http://youngbug.github.io # the base hostname & protocol for your site

##issue评论
comment: true
## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque 关闭掉
# disque: httpyoungbuggithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    #href: /open-source
    #label: My-Project
    href: /footprints
    label: Footprints

  -
    href: /blog
    label: Blog

  -
    href: /favorites
    label: Favorites

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_program_language_keywords: [C, C++, Java, Python, Pascal/Delphi, BASIC, JavaScript]
skill_it_keywords: [Flask, MyBatis, HTML, CSS, Vue.js, axios, Node.js, Redis,MySQL]
skill_cryptography_keywords: [RSA/ECC,AES,3DES,SHA,HMAC,国密SM2/SM3/SM4,OTP,X.509,ASN.1,SSL/TLS,PKI/CA]
skill_smart_card_keywords: [PKCS#11, USB Key, FIDO U2F/UAF, EMV/PBOC, ICAO Doc9303/ePassport, Java Card, Global Platform,ISO/IEC 7816, ISO/IEC 14443,OpenPGP]
skill_certificate_keywords: [法律职业资格]